// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageAlignmentController from "./message_alignment_controller"
application.register("message-alignment", MessageAlignmentController)

import MessagesContainerController from "./messages_container_controller"
application.register("messages-container", MessagesContainerController)

